### ISSUE TITLE
unable to decode units using utf-8

### ISSUE THREAD

**Issue by jamaa** [CNR-Engineering/PyTelTools#1]
First of all, thanks for making this great project available. I had some difficulties installing it under Windows, but now it's working.
At first however, I was unable to load any Serafin files and the program would crash with a python error message regarding var_unit.decode('utf-8')
I found out that the problem was caused by the variable TEMPERATURE, whose unit is °C.
On a whim, I replaced all occurrences in the code of unit.decode('utf-8') with unit.decode('iso-8859-1'), and I can now load Serafin result files just fine. 
Is this perhaps a Windows-specific problem?

**Comment by lucduron** [comment]
Thank you @jamaa for having tried and for providing a solution which fixed your problem.
Indeed I try not to have special characters in title, variable name and unit, but if they are present the script can crash on a UnicodeDecodeError. 
I will try on Windows and Linux and will correct it soon.
By the way, I have also to improve the Serafin parser to handle litte endian and enable some backward compatibily (with old Serafin conventions) and failsoft to read "strange" Serafin files.

**Comment by lucduron** [comment]
I improved the Serafin parser to read big/little endian (automatically determined) and read strings in iso-8859-1 encoding. See commit 65e3cb8.
