### ISSUE TITLE
plot a Serafin results file using Python API

### ISSUE THREAD

**Issue by krober10nd** [CNR-Engineering/PyTelTools#10]
Thanks for the codes and hard work! Is there a script or a command that I can call from the Python interface to produce spatial maps of a given variable? I.e., visualize the free surface evolution in the entire domain?I looked through the codes and GUI but couldn't locate it.

**Comment by lucduron** [comment]
There is no integrated tool to export a figure of a scalar.
However you can visualize a scalar in Mono tab (workflow interface), see https://github.com/CNR-Engineering/PyTelTools/wiki/Visualization#visualize-scalars. You can write this tool from scratch after parsing the Selafin file (https://github.com/CNR-Engineering/PyTelTools/blob/master/notebook/Handle%20Serafin%20files.ipynb), you will need mesh characteristics (mesh coordinates and connectivity table).

**Comment by krober10nd** [comment]
Thanks for the response. I could read the file fine using the notebook command but how do I arrive at this plot? It's fairly unclear in my opinion. It would be beneficial to have the code to make the plot next to the plot, don't you think? 

https://github.com/CNR-Engineering/PyTelTools/wiki/Visualization#visualize-scalars

**Comment by lucduron** [comment]
The plots in PyTelTools are basically performed with **matplotlib** (tricontourf).
Here is a snippet to do it (you have to adapt values to your case) :

```python
import matplotlib.pyplot as plt
from matplotlib import cm
import matplotlib.tri as mtri
from mpl_toolkits.axes_grid1 import make_axes_locatable
import numpy as np

from pyteltools.slf import Serafin


with Serafin.Read('../PyTelTools_validation/data/Yen/fis_yen-exp.slf', 'en') as resin:
    # Read header (SerafinHeader is stored in `header` attribute of `Serafin` class)
    resin.read_header()

    # Display a summary
    print(resin.header.summary())

    # Get time (in seconds) and display it
    resin.get_time()
    print(resin.time)

    values = resin.read_var_in_frame(10, 'B')

    fig, axes = plt.subplots(1)
    fig.set_size_inches(10.0, 6.0)
    levels = np.linspace(np.nanmin(values), np.nanmax(values), 100)

    triang = mtri.Triangulation(resin.header.x, resin.header.y, resin.header.ikle_2d -1)
    axes.tricontourf(triang, values, cmap='terrain', levels=levels)
    axes.set_aspect('equal')

    divider = make_axes_locatable(axes)
    cax = divider.append_axes('right', size='5%', pad=0.2)
    cmap = cm.ScalarMappable(cmap='terrain')
    cmap.set_array(levels)
    fig.colorbar(cmap, cax=cax)

    plt.show()
```

The preview of the result is displayed below:
![yen_visualize_scalar](https://user-images.githubusercontent.com/9614768/128603685-1a2aa615-680c-479f-8ace-14bbce63afc2.png)

Hope it helps.

**Comment by krober10nd** [comment]
Excellent now I understand and can plot some of my solutions. Thank you.
