### ISSUE TITLE
`SerafinHeader.from_triangulation` performance

### ISSUE THREAD

**Issue by krober10nd** [CNR-Engineering/PyTelTools#11]
* I have a mesh with a large amount of islands ~35k and I export it to a Serafin file for use with TELEMAC it takes hours 
* The performance bottleneck is this loop when building `ipobo`.  https://github.com/CNR-Engineering/PyTelTools/blob/cd6cd4824ce1cfdd7845e4d67bed0a29197cdb03/pyteltools/slf/Serafin.py#L623
```
Serafin.Write(output,'en',overwrite=True) as resout:
        output_header = Serafin.SerafinHeader(title='Converted from ADCIRC mesh format') 
        ikle = mesh.elements.triangles.to_numpy()
        xy = mesh.get_xy().to_numpy()
        output_header.from_triangulation(xy, ikle)
```
* Perhaps could be a option to pass your own IPOBO table to the Serafin header class constructor?

**Comment by lucduron** [comment]
Dear Keith,

Thank you for reporting this performance issue, which might occur as I do not have as many boundaries (or islands) in my meshes.
The cost of `build_ipobo` is probably also related to the complex implementation of `iter_on_boundaries` (maybe we can do better).
Do you have in ADCIRC mesh format the information to build the IPOBO table? Or would you like to set the table to 0 and compute it afterwards (in BlueKenue for example)?
Concerning the proposal of adding an argument to provide the IPOBO table, it is a good idea and I think it should be in `from_triangulation`, as some verifications can be done (at least shape of the array).

Best Regards,
Luc

**Comment by krober10nd** [comment]
Hey Luc, 

Thanks for your timely response. 

I can calculate the IPOBO table in Python directly from the IKLE table (I call it entities in my codes). I have some code that perhaps could be inherited here. 

https://github.com/CHLNDDEV/oceanmesh/blob/master/oceanmesh/edges.py#L114

This function computes the edges of the boundary of a mesh in winding order and can handle meshes with many boundaries.  Then it should be walk the edges, increment a counter, and load this into the right position in the IPOBO table. 

I can draft up PR shortly.

**Comment by lucduron** [comment]
I close this issue, because I merged your [pull request](https://github.com/CNR-Engineering/PyTelTools/pull/12) (thank you!).

`SerafinHeader.from_triangulation` has now an option to provide an IPOBO table (and avoid the call to `SerafinHeader.build_ipobo`). Moreover the IPOBO table seems to useless (not read) for Telemac...
