### ISSUE TITLE
Depth-averaging for 3D Serafin files

### ISSUE THREAD

**Issue by krober10nd** [CNR-Engineering/PyTelTools#15]
Is there existing functionality in PyTelTools to depth-average a 3D Serafin file producing a 2D file? Thank you

**Comment by lucduron** [comment]
Dear Keith,

We developed some years ago a CLI script to extract a specific layer or compute the max/min/mean over the vertical:
https://github.com/CNR-Engineering/PyTelTools/blob/01335992e76c1c0be71ec37a6d0774e4c7ccf5e9/cli/slf_3d_to_2d.py

In pyteltools/slf/misc.py there is the computation of the **weights** for the mean:
https://github.com/CNR-Engineering/PyTelTools/blob/01335992e76c1c0be71ec37a6d0774e4c7ccf5e9/pyteltools/slf/misc.py#L685-L697

The depth-averaged is then computed as:
https://github.com/CNR-Engineering/PyTelTools/blob/01335992e76c1c0be71ec37a6d0774e4c7ccf5e9/pyteltools/slf/misc.py#L704-L705

Hope it helps,
Luc

**Comment by krober10nd** [comment]
Thanks! That worked
