### ISSUE TITLE
Add two variables

### ISSUE THREAD

**Issue by krober10nd** [CNR-Engineering/PyTelTools#16]
Hello, 

Is there a API support to multiply two variables in one Serafin file and produce a new input file with the result?   

Thanks

**Comment by lucduron** [comment]
Hello,

If you want to read and write a Serafin file in adding a variable, you could use a command line script such as :
`cli\slf_base.py old.slf new.slf --var2add NEW`

But you have first to defined your new **variable** and **formula** in `pyteltools/slf/variable/variables_2d.py`.

If you do not manage, you can try to write your own script and can help you if you have questions about it.

Best regards,
Luc

**Comment by krober10nd** [comment]
Thank you I managed
