### ISSUE TITLE
Provide example to reproject result 

### ISSUE THREAD

**Issue by krober10nd** [CNR-Engineering/PyTelTools#19]
Hello Luc, Using the workflow gui (and also via the source code) I see various references to geometry.Transformations. After having performed a simulation in geographic space, I'd like to perform some flux calculations and would like to first reproject the results into a UTM coordinate system. 

The workflow GUI has a Transformation node but I'm not sure what the format (or how to create) the input file for it. Could you provide some more details there? Thank you. 
<img width="627" alt="Screenshot 2023-02-25 at 8 51 09 AM" src="https://user-images.githubusercontent.com/18619644/221355305-46fb5f96-8d72-4d19-949a-f1fbd4ce51c8.png">

**Comment by lucduron** [comment]
Dear Keith,

The transformation file is generated by PyTelTools (thought the tool/interface : "Classic Interface > Transform coordinate systems").
It was specifically designed to provide tools for the modeller to perform comparison between physical model (at a given scale and located in a local CRS) and numerical model.
The short documentation of the transformation is here : https://github.com/CNR-Engineering/PyTelTools/wiki/Transform-coordinate-systems.

Best Regards,
Luc
