### ISSUE TITLE
Error in SynchMax

### ISSUE THREAD

**Issue by krober10nd** [CNR-Engineering/PyTelTools#22]
Hi Luc, I'm trying to execute the SynchMax node but it's force closing with this error message in the terminal. Any idea what I  may be doing wrong? Thanks again for all your help, I really think this GUI can be useful there's just a learning curve. 

The max operator works correctly. Another note: the node SynchMax takes almost no time to run. 

<img width="1027" alt="Screenshot 2023-03-01 at 11 02 27 PM" src="https://user-images.githubusercontent.com/18619644/222311682-da0713a4-1d2c-4b8c-bc31-4d373e4685d8.png">
<img width="1340" alt="Screenshot 2023-03-01 at 11 02 52 PM" src="https://user-images.githubusercontent.com/18619644/222311732-1a38e54b-ed74-4ab4-95d1-84dc3fecb67f.png">

**Comment by lucduron** [comment]
The tool "SynchMax" is indeed buggy, I can reproduce the problem. I will fix it soon, thank you for reporting this.

Many tools are very fast as they only add some post-processes for the node "Write Serafin" and "SynchMax" is among them.

**Comment by lucduron** [comment]
I commited a fix for SynchMax, let me know if you still have troubles.

**Comment by krober10nd** [comment]
Thank you Luc!  It now appears to work. I haven't visualized yet the result in BK but will do shortly. However, I used select variables node to also export what I assume is the scalar velocity (norm of velocity vectors) at the time of maximum water depth (based on my selection in the SynchMax node). However I don't see this variable in the resulting output file? 

<img width="644" alt="Screenshot 2023-03-02 at 9 10 28 AM" src="https://user-images.githubusercontent.com/18619644/222425035-ad1492ea-2e92-41b4-81a2-9ce68881c08e.png">


<img width="1337" alt="Screenshot 2023-03-02 at 9 09 59 AM" src="https://user-images.githubusercontent.com/18619644/222424938-5172aa5a-cf79-4f1b-bc72-0e3214de2353.png">

**Comment by lucduron** [comment]
Hi Keith,
Indeed the variables computed on-the-fly are not taken into consideration... I forgot this specific issue which adds a complexity.
I will have a look to include it but I will probably not have time before next week.
A workaround is to add a node "Write Serafin" before "SynchMax" (it will create an intermediate Serafin file) to compute and write this variable.
Regards, Luc

**Comment by CHLNDDEV** [comment]
Perhaps it makes sense to have an additional operator called "norm" which computes the magnitude of a vector? I am trying to study the code to implement it myself but it's quite complex with many pathways.

**Comment by lucduron** [comment]
Dear Keith,
I added a new commit which should fix your problem.
The on-the-fly computed variables are now written and even one of them can be used as the reference variable.
Can you confirm me that everything is OK? (I changed the order of variables, the "EXTRACTED TIME" is now at the end).
The computation of the norm is already implemented, what do you want to modify? Add new custom vectors?
Regards, Luc

**Comment by krober10nd** [comment]
Thank you very much! I will install the latest version and test tomorrow.

**Comment by lucduron** [comment]
Could you test the correction?
If everything is OK, you can close this issue.

**Comment by krober10nd** [comment]
Hey Luc, Sorry for the delay. I tested this workflow using H in the SychMax node and it wrote out a file with all the derived variables so seems correct. 

Thank you!
<img width="590" alt="Screenshot 2023-03-08 at 11 14 50 AM" src="https://user-images.githubusercontent.com/18619644/223735719-045314dc-1303-4ea5-aa16-fc5846f5a266.png">
<img width="880" alt="Screenshot 2023-03-08 at 11 14 22 AM" src="https://user-images.githubusercontent.com/18619644/223735835-494ba414-51bc-4b2b-b80b-c0c714de6feb.png">
