### ISSUE TITLE
Question regarding volume calculation

### ISSUE THREAD

**Issue by krober10nd** [CNR-Engineering/PyTelTools#23]
Hello Luc,

 I'm sorry to keep bothering you but I promise it's a good sign!

 I'm using the code to compute volume in an enclosed polygonal area with the GUI. 

If the grid and results are in geographic space (lat-lon), what are the units of volume? 

Should I reproject the result into a UTM space first then do this calculation? 

Thanks,

Keith

**Comment by lucduron** [comment]
Dear Keith,

I never used the geographic space (lat-lon) with Serafin file, but the volume is consistant only if you have coordinates in meters.
So, yes you should reproject the result into a CRS with coordinates in meters.

Hope it helps!
Regards,
Luc

**Comment by krober10nd** [comment]
Thanks Luc, that's what I figured as well.
