### ISSUE TITLE
Liquid Flux Calculation Orientation 

### ISSUE THREAD

**Issue by krober10nd** [CNR-Engineering/PyTelTools#24]
Hi Luc,

I'm using the flux calculation node in PyTelTools. I'm curious what's the orientation convention for the positive and negative flux values? 

For example is a positive flux going northwards and a negative flux passing southwards (assuming my feature is orientated east-west)?

(y-axis is m^3/s per m overflowing/overtopping rate).
![FLUX_THROUGH_east_TC_1115](https://user-images.githubusercontent.com/18619644/225787172-7e210f46-ff49-44f6-b729-3e720a1a33ce.png)

**Comment by lucduron** [comment]
Indeed the convention was not specified in the [wiki documentation](https://github.com/CNR-Engineering/PyTelTools/wiki/Compute-flux), I added it and rewrite it here: 

> flux thourgh a cross-section is positive if it is designed from left to right bank (ie. cross-section normal vector is oriented at 90° of the original cross-section in the anticlockwise direction)
