### ISSUE TITLE
Change the display of the vertical cross section

### ISSUE THREAD

**Issue by Vittel2** [CNR-Engineering/PyTelTools#4]
I have the problem that my river is much flatter than it is wide. The ratio width to height is about 1:20. The square display of the section is therefore unfavorable for the evaluation. Can the height and width of the image be manually adjusted by the editor, e.g. 5 cm high and 15 cm wide? 
Is the elevation and distance of the section itself changeable? The elevation and distance of my cross sections change as the flow progresses, so I would like to manually adjust them as well, e.g. the elevation of 96-108m to 96-102m.
before:
![cl_section25_before](https://user-images.githubusercontent.com/33861814/33065199-72e48b9e-cea8-11e7-9f64-c0f1909320d1.png)
after:
![cl_section25_after](https://user-images.githubusercontent.com/33861814/33065206-7905edc4-cea8-11e7-8c91-01158bc49aba.png)

**Comment by lucduron** [comment]
Unfortunately the customization possibilites are currently limited. There are a lot of improvements that I have in mind (zoom, change axis, change scale breaks, show/display the mesh structure, ...) to implement to nearly all visualizations, but I will not have time in the coming weeks.

By the way, you can change the height and width of the image in changing the global configuration of PyTelTools with the `FIG_SIZE` keyword (see [how to configure](https://github.com/CNR-Engineering/PyTelTools#configure)).

**Comment by Vittel2** [comment]
Many Thanks. That was very helpful for me.

**Comment by lucduron** [comment]
For your information, the aspect ratio Y/X (or vertical exaggeration) can now be set through the interface if required. New features include also: normal velocity as a plotted variable and/or tangential vectors as arrows. Therefore I close this issue.

![capture d ecran de 2018-06-04 22-00-34](https://user-images.githubusercontent.com/9614768/40938727-ecf652b2-6842-11e8-8f6e-9a5d44f9e0b3.png)
