### ISSUE TITLE
Propose to add get_time_fast() to the Sefafin.py 

### ISSUE THREAD

**Issue by alesok** [CNR-Engineering/PyTelTools#9]
When working with a big serafin file (10-15GB) the reading of the time using ```get_time()``` may take several seconds. Actually we need to read the whole file twice: ones to get time and then again to get 'real' data. So, it would be nice to add a possibility to compute the time instead of reading it from the file. The following code works nicely :)

```python
    def get_time_fast(self):
        """!
        @brief Read the time from first two frames in the Serafin file and compute the time 
        using a time step between first and second frames
        """
        if self.header is None:
            raise SerafinRequestError('Cannot read time without any header (forgot read_header ?)')
        logger.debug('Reading the time series from the file')
        self.file.seek(self.header.header_size, 0)
        for n in range(self.header.nb_frames):
            if n < 2:
                self.file.read(4)
                self.time.append(self.header.unpack_float(self.file.read(self.header.float_size), 1)[0])
                self.file.read(4)
                self.file.seek(self.header.frame_size - 8 - self.header.float_size, 1)
            else:
                self.time.append(self.time[0] + n * (self.time[1] - self.time[0]))
```

**Comment by lucduron** [comment]
Dear @alesok,

Thank you for suggesting a new method for `slf.Serafin.Read`.
The method provided should work fine but can only work if Telemac is used with **a constant time step**.
I prefer not to add the method as it is not the general case. An alternative to this method could be to simply define the list `header.time` manually in your script with something like : 
```python
import numpy as np
header.time = list(np.arange(header.nb_frames)*5.0)  # if time step is equal to 5.0 sec.
```

Finally if you need an iterator on all frames, returning the current time and corresponding values (shape=(header.nb_var, header.nb_nodes)), we could add it, to avoid browsing the file twice.

Regards,
Luc
